# Generated by Django on 2025-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the outfit', null=True),
        ),
    ]
