# Generated by Django 5.2.4 on 2025-07-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_seller'),
    ]

    operations = [
    ]
